"""Initial migration.

Revision ID: d49ad2267f0a
Revises: 
Create Date: 2024-08-09 02:02:51.705483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd49ad2267f0a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weather',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('max_temp', sa.Float(), nullable=False),
    sa.Column('min_temp', sa.Float(), nullable=False),
    sa.Column('precipitation', sa.Float(), nullable=False),
    sa.Column('sunrise', sa.String(length=10), nullable=False),
    sa.Column('sunset', sa.String(length=10), nullable=False),
    sa.Column('condition', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weather')
    # ### end Alembic commands ###
